### App Rules (floating, assign, opacity...)

# Exemple lorsque tu voudras ajouter :
# for_window [class="mpv"] floating enable
# assign [class="Firefox"] 1

# Uncomment this code below if you want no titlebars
#default_border none 

for_window [app_id="rofi"] border none, floating enable, move position 1 ppt 1 ppt

