# Cava — DJ mode / variante 3 « Pulse »
# Barres ultra-fines, mono, framerate élevé, dégradé mauve -> peach.
# Thème « Crépuscule rose ».

[general]
framerate = 90
bars = 0
bar_width = 1
bar_spacing = 0

[input]
method = pulse
source = auto

[output]
method = noncurses
channels = mono
mono_option = average

[color]
background = '#150d24'
gradient = 1
gradient_count = 4
gradient_color_1 = '#7e4ca0'
gradient_color_2 = '#b35298'
gradient_color_3 = '#e3779e'
gradient_color_4 = '#efaaa2'

[smoothing]
noise_reduction = 60
monstercat = 0
waves = 0
