# Cava — DJ mode / variante 4 « Lune »
# Barres épaisses, descente lente, tons lune (peach / lilas).
# Thème « Crépuscule rose ».

[general]
framerate = 45
bars = 0
bar_width = 7
bar_spacing = 2

[input]
method = pulse
source = auto

[output]
method = noncurses
channels = stereo
mono_option = average

[color]
background = '#150d24'
gradient = 1
gradient_count = 5
gradient_color_1 = '#323169'
gradient_color_2 = '#7e4ca0'
gradient_color_3 = '#b35298'
gradient_color_4 = '#efaaa2'
gradient_color_5 = '#c9add1'

[smoothing]
noise_reduction = 95
monstercat = 1
waves = 0
